### ISSUE TITLE
About the training time 

### ISSUE THREAD

**Issue by zhangjb416** [XiangyangLi20/KERM#2]
Thanks for sharing your great work!
Could you please tell me how long do the pre-training stage and fine-tuning stage take?

When I pre-train a model on REVERIE using the provided scrips, I find it costs much more time than the baseline DUET. Especially, the data loading process in "get_traj_pano_fts" that loads the knowledge feature is time-consuming. Is this normal?

Thanks!

**Comment by MrZihan** [comment]
Due to the large size of feature files, file reading becomes the main bottleneck during training.
We recommend optimizing the training speed from the following aspects: 1) cache features into memory (this requires a machine with very sufficient memory, greater than 512GB); 2) Using multithreading to read feature files, we consider updating this functionality later in the code.
